// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaEnWT8ir1swG-teJITjOLT_72nTS7p9o',
    appId: '1:513239031410:web:14152a79567fa10214eceb',
    messagingSenderId: '513239031410',
    projectId: 'budongsan-flutter',
    authDomain: 'budongsan-flutter.firebaseapp.com',
    storageBucket: 'budongsan-flutter.firebasestorage.app',
    measurementId: 'G-ZH5XM0RRK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-EpwG70va-_rudwOoQy_dfVBuORKMu5w',
    appId: '1:513239031410:android:1fd837a8626bdb7e14eceb',
    messagingSenderId: '513239031410',
    projectId: 'budongsan-flutter',
    storageBucket: 'budongsan-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2y9e4-4n4o5NHCLgsAQFsWFqqEm3wRAc',
    appId: '1:513239031410:ios:71ddfc362629586914eceb',
    messagingSenderId: '513239031410',
    projectId: 'budongsan-flutter',
    storageBucket: 'budongsan-flutter.firebasestorage.app',
    iosBundleId: 'com.example.mybudongsan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2y9e4-4n4o5NHCLgsAQFsWFqqEm3wRAc',
    appId: '1:513239031410:ios:71ddfc362629586914eceb',
    messagingSenderId: '513239031410',
    projectId: 'budongsan-flutter',
    storageBucket: 'budongsan-flutter.firebasestorage.app',
    iosBundleId: 'com.example.mybudongsan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaEnWT8ir1swG-teJITjOLT_72nTS7p9o',
    appId: '1:513239031410:web:e11674960e3b35c614eceb',
    messagingSenderId: '513239031410',
    projectId: 'budongsan-flutter',
    authDomain: 'budongsan-flutter.firebaseapp.com',
    storageBucket: 'budongsan-flutter.firebasestorage.app',
    measurementId: 'G-8ZBW8XWSQ4',
  );
}
